# Generated by Django 4.2.6 on 2024-07-17 17:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_image_remove_topic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='topic_logos/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter the content of the article using Rich Text format.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the article was published.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='Default summary', help_text='Enter a summary for the article.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', help_text='Enter the article title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(help_text='Select the topic for this article.', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.topic'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times the article has been viewed.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(default='Default content', help_text='Enter the topic content.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(default='Default description', help_text='Enter the topic description.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', help_text='Enter the topic title.', max_length=200),
        ),
    ]
