# Generated by Django 5.0.6 on 2024-06-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_topic'),
    ]

    operations = [
    ]
