# Generated by Django 5.0.6 on 2024-07-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default='Default summary'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
